### ISSUE TITLE
Uncaught Exception occured!

### ISSUE THREAD

**Issue by BRlombardi86** [Twig6943/AffinityOnLinux#20]
I've followed the step-by-step guide and got this error while trying to run Affinity Publisher

A uncaught exception occured:
Error: spawn /var/home/lomba/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/ElementalWarriorWine/bin/wineserver ENOENT
Report the exception on our Github repository.

Sorry, but I don't know what is wrong or what should I do to fix it.

**Comment by Twig6943** [comment]
Report the exception on our Github repository

pls report that to elementalwarriors wine repository i stead

I say you use wine-tkg-affinity for the time  being.
