### ISSUE TITLE
Installation failed: File not found

### ISSUE THREAD

**Issue by DerDa81** [Twig6943/AffinityOnLinux#23]
Hi, i get this Error on Publisher:
bash -c "$(curl -s https://raw.githubusercontent.com/ryzendew/AffinityOnLinux/refs/heads/main/AffinityScripts/AffinityPublisher.sh)"
All dependencies are installed!
bash: Zeile 39: jq: Befehl nicht gefunden
File not found in the latest release

**Comment by Twig6943** [comment]
The script is unsupported. Use the guide methods also we provide support only over at out discord/matrix
