### ISSUE TITLE
Bottles install broken ?

### ISSUE THREAD

**Issue by faeizmahrus** [Twig6943/AffinityOnLinux#24]
I followed the guide thoroughly, but it gave me the following error when I tried to run Affinity Photo 2.3.1 installer :
` 0120:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"SetupUI.exe" cannot be loaded `

When I checked the System32 directory of the wine prefix, mscoree.dll existed there.

Guide I followed : https://github.com/Twig6943/AffinityOnLinux/blob/main/Guides/Bottles/Guide.md
( I used Flatpak Bottles + ElementalWarrior wine )

**Comment by Twig6943** [comment]
Try another guide, support is provided over at out matrix/discord.
